### ISSUE TITLE
Error when install base with pyopensql 19.0.0

### ISSUE THREAD

**Issue by MihaitaTudor** [OCA/OCB#1133]
Impacted versions:15

Current behavior:
2022-09-12 10:52:14,432 561786 CRITICAL ? odoo.modules.module: Couldn't load module base.
2022-09-12 10:52:14,432 561786 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG
2022-09-12 10:52:14,432 561786 ERROR ? odoo.service.server: Failed to load server-wide module `base`..
Traceback (most recent call last):
  File "/home/mtudor/checkouts/LiveMedPy12092022/no_repo/odoo/src/OCB/odoo/service/server.py", line 1210,
    odoo.modules.module.load_openerp_module(m)
  File "/home/mtudor/checkouts/LiveMedPy12092022/no_repo/odoo/src/OCB/odoo/modules/module.py", line 396,
    __import__('odoo.addons.' + module_name)
  File "/home/mtudor/checkouts/LiveMedPy12092022/no_repo/odoo/src/OCB/odoo/addons/base/__init__.py", line
    from . import models
  File "/home/mtudor/checkouts/LiveMedPy12092022/no_repo/odoo/src/OCB/odoo/addons/base/models/__init__.py
    from . import ir_mail_server
  File "/home/mtudor/checkouts/LiveMedPy12092022/no_repo/odoo/src/OCB/odoo/addons/base/models/ir_mail_ser
    from OpenSSL import crypto as SSLCrypto
  File "/home/mtudor/checkouts/LiveMedPy12092022/no_repo/odoo/env/lib/python3.8/site-packages/OpenSSL/__i
    from OpenSSL import crypto, SSL
  File "/home/mtudor/checkouts/LiveMedPy12092022/no_repo/odoo/env/lib/python3.8/site-packages/OpenSSL/cry
    class X509StoreFlags(object):
  File "/home/mtudor/checkouts/LiveMedPy12092022/no_repo/odoo/env/lib/python3.8/site-packages/OpenSSL/cry
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
2022-09-12 10:52:14,469 561786 CRITICAL ? odoo.modules.module: Couldn't load module web.
2022-09-12 10:52:14,469 561786 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG
2022-09-12 10:52:14,470 561786 ERROR ? odoo.service.server: Failed to load server-wide module `web`.

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Please check on odoo/odoo and put the issue there if not exists.
