### ISSUE TITLE
 Errors When Installing Multiple Modules (Sales, Invoicing, Inventory, Purchase, Manufacturing, Maintenance) on Odoo OCB V14.0

### ISSUE THREAD

**Issue by the-kizz** [OCA/OCB#1182]
## Module
When simultaneously installing Sales, Invoicing, Inventory, Purchase, Manufacturing, Maintenance

## Describe the bug
When attempting to install multiple Odoo modules at once on a fresh installation of Odoo OCB V14.0, the installation stalls with a warning message. Restarting the server leads to two different errors when accessing and reinstalling the Inventory module.

## To Reproduce
**Affected versions**: Odoo OCB V14.0

**1.** Start with a fresh install of Odoo OCB V14.0.
**2.** Attempt to install the following modules simultaneously: Sales, Invoicing, Inventory, Purchase, Manufacturing, Maintenance.
**3.** Encounter the following warning:
Odoo is currently processing a scheduled action.
Module operations are not possible at this time, please try again later or contact your system administrator

**4.** Restart the server, and observe the following error when accessing the Inventory module:
Error:
          Odoo Server Error
          
          Traceback (most recent call last):
            File "/odoo14/odoo14-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
              result = request.dispatch()
            File "/odoo14/odoo14-server/odoo/http.py", line 696, in dispatch
              result = self._call_function(**self.params)
            File "/odoo14/odoo14-server/odoo/http.py", line 370, in _call_function
              return checked_call(self.db, *args, **kwargs)
            File "/odoo14/odoo14-server/odoo/service/model.py", line 94, in wrapper
              return f(dbname, *args, **kwargs)
            File "/odoo14/odoo14-server/odoo/http.py", line 358, in checked_call
              result = self.endpoint(*a, **kw)
            File "/odoo14/odoo14-server/odoo/http.py", line 919, in __call__
              return self.method(*args, **kw)
            File "/odoo14/odoo14-server/odoo/http.py", line 544, in response_wrap
              response = f(*args, **kw)
            File "/odoo14/odoo14-server/addons/web/controllers/main.py", line 1720, in load
              action = request.env[action_type].sudo().browse([action_id]).read()
            File "/odoo14/odoo14-server/odoo/addons/base/models/ir_actions.py", line 240, in read
              result = super(IrActionsActWindow, self).read(fields, load=load)
            File "/odoo14/odoo14-server/odoo/models.py", line 3026, in read
              return self._read_format(fnames=fields, load=load)
            File "/odoo14/odoo14-server/odoo/models.py", line 3046, in _read_format
              vals[name] = convert(record[name], record, use_name_get)
            File "/odoo14/odoo14-server/odoo/models.py", line 5702, in __getitem__
              return self._fields[key].__get__(self, type(self))
            File "/odoo14/odoo14-server/odoo/fields.py", line 1042, in __get__
              self.compute_value(recs)
            File "/odoo14/odoo14-server/odoo/fields.py", line 1198, in compute_value
              records._compute_field_value(self)
            File "/odoo14/odoo14-server/odoo/models.py", line 4079, in _compute_field_value
              odoo.fields.determine(field.compute, self)
            File "/odoo14/odoo14-server/odoo/fields.py", line 82, in determine
              return needle(*args)
            File "/odoo14/odoo14-server/odoo/addons/base/models/ir_actions.py", line 207, in _compute_search_view
              fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
            File "/odoo14/odoo14-server/odoo/api.py", line 476, in __getitem__
              return self.registry[model_name]._browse(self, (), ())
            File "/odoo14/odoo14-server/odoo/modules/registry.py", line 177, in __getitem__
              return self.models[model_name]
          Exception
          
          The above exception was the direct cause of the following exception:
          
          Traceback (most recent call last):
            File "/odoo14/odoo14-server/odoo/http.py", line 652, in _handle_exception
              return super(JsonRequest, self)._handle_exception(exception)
            File "/odoo14/odoo14-server/odoo/http.py", line 317, in _handle_exception
              raise exception.with_traceback(None) from new_cause
          KeyError: 'stock.picking.type'

**5.** Attempt to reinstall the Inventory module and encounter the following server error:
          Error:
          Odoo Server Error

            Traceback (most recent call last):
              File "/odoo14/odoo14-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
                result = request.dispatch()
              File "/odoo14/odoo14-server/odoo/http.py", line 696, in dispatch
                result = self._call_function(**self.params)
              File "/odoo14/odoo14-server/odoo/http.py", line 370, in _call_function
                return checked_call(self.db, *args, **kwargs)
              File "/odoo14/odoo14-server/odoo/service/model.py", line 94, in wrapper
                return f(dbname, *args, **kwargs)
              File "/odoo14/odoo14-server/odoo/http.py", line 358, in checked_call
                result = self.endpoint(*a, **kw)
              File "/odoo14/odoo14-server/odoo/http.py", line 919, in __call__
                return self.method(*args, **kw)
              File "/odoo14/odoo14-server/odoo/http.py", line 544, in response_wrap
                response = f(*args, **kw)
              File "/odoo14/odoo14-server/addons/web/controllers/main.py", line 1728, in run
                result = action.run()
              File "/odoo14/odoo14-server/odoo/addons/base/models/ir_actions.py", line 632, in run
                res = runner(run_self, eval_context=eval_context)
              File "/odoo14/odoo14-server/odoo/addons/base/models/ir_actions.py", line 501, in _run_action_code_multi
                safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
              File "/odoo14/odoo14-server/odoo/tools/safe_eval.py", line 347, in safe_eval
                raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
            Exception
            
            The above exception was the direct cause of the following exception:
            
            Traceback (most recent call last):
              File "/odoo14/odoo14-server/odoo/http.py", line 652, in _handle_exception
                return super(JsonRequest, self)._handle_exception(exception)
              File "/odoo14/odoo14-server/odoo/http.py", line 317, in _handle_exception
                raise exception.with_traceback(None) from new_cause
            ValueError: <class 'odoo.tools.convert.ParseError'>: "while parsing /odoo14/odoo14-server/addons/stock/data/stock_data.xml:206, near
            <record id="warehouse0" model="stock.warehouse">
                        <field name="partner_id" ref="base.main_partner"/>
                        <field name="name">San Francisco</field>
                        <field name="code">WH</field>
                    </record>" while evaluating
            'records.button_immediate_install()'

**Expected behavior**
The modules should install smoothly without any warnings or errors, and the installed modules should be accessible without any issues.

**Additional context**
- OS: Linux (server), Windows (client)
- Browser: Chrome
- Python Version: 3.8.10

**Comment by pedrobaeza** [comment]
Please publish this on odoo/odoo, as they are not OCB exclusive issues.

**Comment by the-kizz** [comment]
> Please publish this on odoo/odoo, as they are not OCB exclusive issues.

It occurs on ocb. Not ODOO. 

Did you try replicate or just close? 

Regardless, Isn’t ocb back ports meant to address issues that will no longer be addressed by Odoo as they are old versions?

**Comment by pedrobaeza** [comment]
Starting with, 14.0 is still supported by Odoo, but yes, that's intended, but you are not putting any solution, just an issue.

> It occurs on ocb. Not ODOO.

That can't be. There's no change on that modules in this OCB version. You can check the differences, that are minimum.
