### ISSUE TITLE
Budgets crash when using a budget position with no accounts

### ISSUE THREAD

**Issue by clonedagain** [OCA/OCB#14]
OCB introduced a feature to take sub-accounts in budget lines, but there is a small mistake in the patch, because _get_children_and_consol crashes when passed an empty list.
It can be fixed by simply calling _get_children_and_consol after testing the list truth value, instead of before.

Traceback:
Client Traceback (most recent call last):
  File "/home/openerp/openerp-web/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/home/openerp/openerp-web/addons/web/controllers/main.py", line 1128, in call_kw
    return self._call_kw(req, model, method, args, kwargs)
  File "/home/openerp/openerp-web/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/home/openerp/openerp-web/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/home/openerp/openerp-web/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/home/openerp/openerp-web/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/home/openerp/openerp-web/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/home/openerp/openobject-server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/openerp/openobject-server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/home/openerp/openobject-server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/openerp/openobject-server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/openerp/openobject-server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/openerp/openobject-server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/openerp/openobject-server/openerp/osv/orm.py", line 3680, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/home/openerp/openobject-server/openerp/osv/orm.py", line 3801, in _read_flat
    res2 = self._columns[f].get(cr, self, ids, f, user, context=context, values=res)
  File "/home/openerp/openobject-server/openerp/osv/fields.py", line 1145, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/openerp/openobject-addons/account_budget/account_budget.py", line 156, in _prac
    res[line.id] = self._prac_amt(cr, uid, [line.id], context=context)[line.id]
  File "/home/openerp/account-financial-tools/account_budget_purchase/account_budget.py", line 70, in _prac_amt
    context=context)
  File "/home/openerp/openobject-addons/account_budget/account_budget.py", line 120, in _prac_amt
    acc_ids = account_obj._get_children_and_consol(cr, uid, acc_ids, context=context)
  File "/home/openerp/openobject-addons/account/account.py", line 265, in _get_children_and_consol
    ids2 = self.search(cr, uid, [('parent_id', 'child_of', ids)], context=context)
  File "/home/openerp/openobject-addons/account/account.py", line 261, in search
    order, context=context, count=count)
  File "/home/openerp/openobject-server/openerp/osv/orm.py", line 2372, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/openerp/openobject-server/openerp/osv/orm.py", line 4936, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/home/openerp/openobject-server/openerp/osv/orm.py", line 4764, in _where_calc
    where_clause, where_params = e.to_sql()
  File "/home/openerp/openobject-server/openerp/osv/expression.py", line 1232, in to_sql
    q2 = stack.pop()
IndexError: pop from empty list

**Comment by clonedagain** [comment]
Merged some time ago.
