### ISSUE TITLE
[8.0] Odoo Server Error un Runbot OCA

### ISSUE THREAD

**Issue by rafaelbn** [OCA/OCB#379]
- Go to runbot OCA, login as admin and try to do anything

```
Odoo

Odoo Server Error

Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3119674-8-0-88f836/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3119674-8-0-88f836/openerp/http.py", line 1415, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/srv/openerp/instances/openerp-oca-runbot/sandbox/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
```

**Comment by pedrobaeza** [comment]
I have rebuilt and it's working fine.  Please be sure before making an issue.

**Comment by rafaelbn** [comment]
I copied and pasted the Traceback, that is why I opened the issue, because it was. It is happening now in this instance:
- http://3119674-8-0-88f836.runbot1.odoo-community.org/?db=3119674-8-0-88f836-all

![2015-11-14_12-46-05](https://cloud.githubusercontent.com/assets/8736623/11163395/bf8d8836-8acd-11e5-82fc-f2738c2165a9.png)

**Comment by rafaelbn** [comment]
Please, reopen the issue is still there:
- Go To runbot OCA
- Open an loging as admin

**Comment by rafaelbn** [comment]
Is from here:

![2015-11-14_12-53-06](https://cloud.githubusercontent.com/assets/8736623/11163426/ef04ada0-8ace-11e5-9c2c-9942f5859a87.png)

**Comment by acysos** [comment]
I have the same issue in local installation of the last OCB.

Greetgins

**Comment by rafaelbn** [comment]
This was an error in runbot that was solved, we don't have any issue in our environments.
