### ISSUE TITLE
OCB change in stock_account._get_invoice_vals( cause incompatibility with standard Odoo.

### ISSUE THREAD

**Issue by NL66278** [OCA/OCB#538]
Impacted versions: 8.0

Steps to reproduce: Override methode _invoice_create_line in stock.py and pass the original 4 element tuple to the key argument of _get_invoice_vals.

Current behavior: Crash with message: ValueError: too many values to unpack

Expected behavior: Valid values for invoice are returned

The problem was introduced by commit 95cabdacd. This commit was meant to prevent grouping by user_id if several users created purchase orders for the same supplier, and the supplier sent a consolidated invoice.

The solution would be to partially revert this commit. The fact that the method _get_invoice_vals expects a four element tuple in key (I will not comment what I think about this method of argument passing) should be considered part of the 'contract' for calling this method, and therefore not changed if not absolutely necesarry.

Video/Screenshot link (optional):

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoariacp80/odoo/parts/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/home/odoariacp80/odoo/parts/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoariacp80/odoo/parts/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/addons/stock_account/wizard/stock_invoice_onshipping.py", line 105, in open_invoice
    invoice_ids = self.create_invoice(cr, uid, ids, context=context)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/addons/stock_account/wizard/stock_invoice_onshipping.py", line 148, in create_invoice
    context=context)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/addons/account_anglo_saxon/stock.py", line 46, in action_invoice_create
    res = super(stock_picking,self).action_invoice_create(cr, uid, ids, journal_id, group, type, context=context)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/addons/stock_account/stock.py", line 280, in action_invoice_create
    invoices += self._invoice_create_line(cr, uid, moves, journal_id, type, context=context)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/addons/delivery/stock.py", line 135, in _invoice_create_line
    invoice_ids = super(stock_picking, self)._invoice_create_line(cr, uid, moves, journal_id, inv_type=inv_type, context=context)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/addons-onestein/address_consolidation/stock.py", line 88, in _invoice_create_line
    invoice_vals = self._get_invoice_vals(key, inv_type, journal_id, move, picking=move.picking_id)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/addons-onestein/address_consolidation/stock.py", line 62, in _get_invoice_vals
    res = super(stock_picking, self)._get_invoice_vals(key, inv_type, journal_id, move)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/addons/sale_stock/sale_stock.py", line 503, in _get_invoice_vals
    inv_vals = super(stock_picking, self)._get_invoice_vals(cr, uid, key, inv_type, journal_id, move, context=context)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/1200wd_addons/sale_channel/models/stock.py", line 37, in _get_invoice_vals
    inv_vals = super(StockPicking, self)._get_invoice_vals(key, inv_type, journal_id, move)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/addons/purchase/stock.py", line 223, in _get_invoice_vals
    inv_vals = super(stock_picking, self)._get_invoice_vals(cr, uid, key, inv_type, journal_id, move, context=context)
  File "/home/odoariacp80/odoo/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoariacp80/odoo/parts/odoo/addons/stock_account/stock.py", line 286, in _get_invoice_vals
    partner, currency_id, company_id = key
ValueError: too many values to unpack
```

**Comment by hbrunn** [comment]
so to keep compatibility, we should return `False` at the place in the tuple where upstream returns the `user_id`, right?

**Comment by NL66278** [comment]
Instead of False I give the original user_id, minimizing the difference with standard Odoo, just ignoring the value passed.

**Comment by NL66278** [comment]
Issue has been solved by merged PR.
