### ISSUE TITLE
"[FIX] website: use CDN for assets " causes: QWebException: 'function' object has no attribute 'clear_cache'

### ISSUE THREAD

**Issue by awa-si** [OCA/OCB#593]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by awa-si** [comment]
Traceback:
==================================================================
2017-02-28 23:48:37,268 49043 ERROR awwea odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/var/opt/odoo/10/env/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/var/opt/odoo/10/env/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/var/opt/odoo/10/env/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/var/opt/odoo/10/env/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/opt/odoo/10/env/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/opt/odoo/10/env/odoo/http.py", line 327, in checked_call
    result.flatten()
  File "/var/opt/odoo/10/env/odoo/http.py", line 1257, in flatten
    self.response.append(self.render())
  File "/var/opt/odoo/10/env/odoo/http.py", line 1250, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/var/opt/odoo/10/env/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/var/opt/odoo/10/env/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
    return self.env[engine].render(self.id, qcontext)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: 'function' object has no attribute 'clear_cache'
Traceback (most recent call last):
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_website_layout_38
  File "<template>", line 3, in body_call_content_37
  File "<template>", line 19, in set_12
  File "/var/opt/odoo/10/env/addons/website/models/ir_qweb.py", line 30, in _get_asset
    return super(QWeb, self)._get_asset(xmlid, options, css, js, debug, async, values)
  File "<decorator-gen-20>", line 2, in _get_asset
  File "/var/opt/odoo/10/env/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 194, in _get_asset
    return asset.to_html(css=css, js=js, debug=debug, async=async, url_for=(values or {}).get('url_for', lambda url: url))
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 121, in to_html
    css_attachments = self.css()
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 268, in css
    self.save_attachment("css", ' '.join(page), inc=idx)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 227, in save_attachment
    self.clean_attachments(type)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 179, in clean_attachments
    self.env['ir.qweb']._get_asset.clear_cache(self.env['ir.qweb'])
AttributeError: 'function' object has no attribute 'clear_cache'

Error to render compiling AST
AttributeError: 'function' object has no attribute 'clear_cache'
Template: website.layout
Path: /templates/t/t/t[5]/t[4]
Node: <t t-call-assets="web.assets_common" t-js="false"/>
            

2017-02-28 23:48:39,220 49043 ERROR awwea odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/var/opt/odoo/10/env/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/var/opt/odoo/10/env/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/var/opt/odoo/10/env/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/var/opt/odoo/10/env/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/opt/odoo/10/env/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/opt/odoo/10/env/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/var/opt/odoo/10/env/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/var/opt/odoo/10/env/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/var/opt/odoo/10/env/addons/website/controllers/main.py", line 73, in index
    return request.env['ir.http'].reroute(first_menu.url)
  File "/var/opt/odoo/10/env/addons/website/models/ir_http.py", line 238, in reroute
    return cls._dispatch()
  File "/var/opt/odoo/10/env/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/var/opt/odoo/10/env/addons/website/models/ir_http.py", line 218, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/var/opt/odoo/10/env/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/var/opt/odoo/10/env/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/var/opt/odoo/10/env/addons/website/models/ir_http.py", line 326, in _handle_exception
    html = request.env['ir.ui.view'].render_template('website.http_error', values)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/var/opt/odoo/10/env/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/var/opt/odoo/10/env/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
    return self.env[engine].render(self.id, qcontext)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: 'function' object has no attribute 'clear_cache'
Traceback (most recent call last):
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_website_layout_38
  File "<template>", line 3, in body_call_content_37
  File "<template>", line 19, in set_12
  File "/var/opt/odoo/10/env/addons/website/models/ir_qweb.py", line 30, in _get_asset
    return super(QWeb, self)._get_asset(xmlid, options, css, js, debug, async, values)
  File "<decorator-gen-20>", line 2, in _get_asset
  File "/var/opt/odoo/10/env/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 194, in _get_asset
    return asset.to_html(css=css, js=js, debug=debug, async=async, url_for=(values or {}).get('url_for', lambda url: url))
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 121, in to_html
    css_attachments = self.css()
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 268, in css
    self.save_attachment("css", ' '.join(page), inc=idx)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 227, in save_attachment
    self.clean_attachments(type)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 179, in clean_attachments
    self.env['ir.qweb']._get_asset.clear_cache(self.env['ir.qweb'])
AttributeError: 'function' object has no attribute 'clear_cache'

Error to render compiling AST
AttributeError: 'function' object has no attribute 'clear_cache'
Template: website.layout
Path: /templates/t/t/t[5]/t[6]
Node: <t t-call-assets="web_editor.summernote" t-js="false" groups="website.group_website_publisher"/>
            

2017-02-28 23:48:39,972 49043 ERROR awwea werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/var/opt/odoo/10/env/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/var/opt/odoo/10/env/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/var/opt/odoo/10/env/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/var/opt/odoo/10/env/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/var/opt/odoo/10/env/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/var/opt/odoo/10/env/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/var/opt/odoo/10/env/addons/website/models/ir_http.py", line 218, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/var/opt/odoo/10/env/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/var/opt/odoo/10/env/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/var/opt/odoo/10/env/addons/website/models/ir_http.py", line 326, in _handle_exception
    html = request.env['ir.ui.view'].render_template('website.http_error', values)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/var/opt/odoo/10/env/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/var/opt/odoo/10/env/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
    return self.env[engine].render(self.id, qcontext)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: 'function' object has no attribute 'clear_cache'
Traceback (most recent call last):
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_website_layout_38
  File "<template>", line 3, in body_call_content_37
  File "<template>", line 19, in set_12
  File "/var/opt/odoo/10/env/addons/website/models/ir_qweb.py", line 30, in _get_asset
    return super(QWeb, self)._get_asset(xmlid, options, css, js, debug, async, values)
  File "<decorator-gen-20>", line 2, in _get_asset
  File "/var/opt/odoo/10/env/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 194, in _get_asset
    return asset.to_html(css=css, js=js, debug=debug, async=async, url_for=(values or {}).get('url_for', lambda url: url))
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 121, in to_html
    css_attachments = self.css()
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 268, in css
    self.save_attachment("css", ' '.join(page), inc=idx)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 227, in save_attachment
    self.clean_attachments(type)
  File "/var/opt/odoo/10/env/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 179, in clean_attachments
    self.env['ir.qweb']._get_asset.clear_cache(self.env['ir.qweb'])
AttributeError: 'function' object has no attribute 'clear_cache'

Error to render compiling AST
AttributeError: 'function' object has no attribute 'clear_cache'
Template: website.layout
Path: /templates/t/t/t[5]/t[7]
Node: <t t-call-assets="web_editor.assets_editor" t-js="false" groups="website.group_website_publisher"/>

**Comment by awa-si** [comment]
Fixed with latest commit

**Comment by alfaser123** [comment]
hello I am experiencing this issue. could you please give me information about "fixed with latest commit"??  What is the work arround  to fix it?  thanks
