### ISSUE TITLE
[10.0][l10n_it] Failing reconciliation test

### ISSUE THREAD

**Issue by WohthaN** [OCA/OCB#640]
Impacted versions:
10.0 @ 62b414ea170d3e898006d536de99ebd47fa9040f (and tested least  4 weeks back in history)

Steps to reproduce:
```
git clone https://github.com/OCA/OCB.git OCB 
git checkout 62b414ea170d3e898006d536de99ebd47fa9040f #if necessary
cd OCB
./odoo-bin --addons-path=./addons/ --log-level=test --logfile=/dev/stdout --stop-after-init --test-enable -d test --init=base_vat,base_iban,l10n_it
```
where `test` is a not-yet-created database. 

Current behavior:
Test fails with:
```
odoo.addons.account.tests.test_reconciliation: ERROR
odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_chf_transaction_chf (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_eur_transaction_eur (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_usd_transaction_eur (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
odoo.addons.account.tests.test_reconciliation: test_statement_usd_invoice_usd_transaction_usd (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
odoo.addons.account.tests.test_reconciliation: ======================================================================
odoo.addons.account.tests.test_reconciliation: ERROR: test_statement_euro_invoice_usd_transaction_euro_full (odoo.addons.account.tests.test_reconciliation.TestReconciliation)
odoo.addons.account.tests.test_reconciliation: Traceback (most recent call last):
odoo.addons.account.tests.test_reconciliation: `   File "/tmp/OCB/addons/account/tests/test_reconciliation.py", line 252, in test_statement_euro_invoice_usd_transaction_euro_full
odoo.addons.account.tests.test_reconciliation: `     self.assertTrue(invoice_rec_line.reconciled, 'The invoice should be totally reconciled')
odoo.addons.account.tests.test_reconciliation: `   File "/tmp/OCB/odoo/fields.py", line 864, in __get__
odoo.addons.account.tests.test_reconciliation: `     record.ensure_one()
odoo.addons.account.tests.test_reconciliation: `   File "/tmp/OCB/odoo/models.py", line 4826, in ensure_one
odoo.addons.account.tests.test_reconciliation: `     raise ValueError("Expected singleton: %s" % self)
odoo.addons.account.tests.test_reconciliation: ` ValueError: Expected singleton: account.move.line(113, 112)
odoo.addons.account.tests.test_reconciliation: FAILED
odoo.addons.account.tests.test_reconciliation:  (errors=1, skipped=1)
odoo.modules.module: odoo.addons.account.tests.test_reconciliation tested in 22.49s, 28146 queries
odoo.modules.module: Module account: 0 failures, 1 errors
```

Expected behavior:
Test passes. 

Note: 
without the `l10n_it` module (but with the dependencies declared in the module) tests are passing:
```
./odoo-bin --addons-path=./addons/ --log-level=test --logfile=/dev/stdout --stop-after-init --test-enable -d test --init=base_vat,base_iban
```
and the logs are different only by a few timestamps, proving that no additional dependency is brought in by the module

[log_with_l10n_it.txt](https://github.com/OCA/OCB/files/1201016/log_with_l10n_it.txt)
[log_without_l10n_it.txt](https://github.com/OCA/OCB/files/1201017/log_without_l10n_it.txt)

**Comment by eLBati** [comment]
Hi @WohthaN
Is this strictly related to OCB?
Otherwise you should open an issue at https://github.com/odoo/odoo

**Comment by WohthaN** [comment]
Indeed the problem happens even in the odoo repo, it's not strictly an OCB issue. Moving the issue there:
https://github.com/odoo/odoo/issues/18845

Thanks @eLBati for the suggestion!
