### ISSUE TITLE
float_round() got an unexpected keyword argument 'rounding_method'

### ISSUE THREAD

**Issue by cubells** [OCA/OCB#65]
Strange Bug with the last version of 7.0 branch:

Traceback (most recent call last):
  File "/opt/openerp/src/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/src/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/src/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/src/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/src/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/src/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/src/core/addons/warning/warning.py", line 279, in product_id_change
    lang, update_tax, date_order, packaging, fiscal_position, flag, context=context)
  File "/opt/openerp/src/core/addons/sale_stock/sale_stock.py", line 622, in product_id_change
    compare_qty = float_compare(product_obj.virtual_available, qty, precision_rounding=uom2.rounding)
  File "/opt/openerp/src/server/openerp/osv/orm.py", line 502, in **getattr**
    return self[name]
  File "/opt/openerp/src/server/openerp/osv/orm.py", line 405, in **getitem**
    field_values = self._table.read(self._cr, self._uid, ids, field_names, context=self._context, load="_classic_write")
  File "/opt/openerp/src/server/openerp/osv/orm.py", line 3680, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/opt/openerp/src/server/openerp/osv/orm.py", line 3789, in _read_flat
    res2 = self._columns[val[0]].get(cr, self, ids, val, user, context=context, values=res)
  File "/opt/openerp/src/server/openerp/osv/fields.py", line 1145, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/openerp/src/core/addons/stock/product.py", line 361, in _product_available
    stock = self.get_product_available(cr, uid, ids, context=c)
  File "/opt/openerp/src/core/addons/stock/product.py", line 331, in get_product_available
    uoms_o[context.get('uom', False) or product2uom[prod_id]], context=context)
  File "/opt/openerp/src/core/addons/product/product.py", line 185, in _compute_qty_obj
    amount = ceiling(amount \* to_unit.factor, to_unit.rounding)
  File "/opt/openerp/src/core/addons/product/_common.py", line 32, in ceiling
    return tools.float_round(f, precision_rounding=r, rounding_method='UP')
TypeError: float_round() got an unexpected keyword argument 'rounding_method'

Float function has the correct header:

def float_round(value, precision_digits=None, precision_rounding=None, rounding_method='HALF-UP'):

and _common.py has a correct call:

return tools.float_round(f, precision_rounding=r, rounding_method='UP')

but I've got this error on create a new sale order.

is It possible?

**Comment by clonedagain** [comment]
Probably related to https://github.com/odoo/odoo/pull/2976, though I'm not sure in which way.

**Comment by pedrobaeza** [comment]
Hi, Vicent,

Have you tried to replicate it on a runbot instance? Can you give us the path you have followed?

Regards.

**Comment by cubells** [comment]
-- Have you tried to replicate it on a runbot instance?
No, I haven't.
-- Can you give us the path you have followed?

Yes, I can.

An openerp instance in production with the old bazar code.

I've updated all the code with the new versions in github.

Restart the server with --update=all without any error problem.
All works, but...

When a user try to create a sale order and select the product to insert a line in sale_order, bump...

I get this error. It's on the onchange function of product_id

But, the error is raised too when user creates a purchase, an invoice, an stock_picking..

I've read the code and I haven't found any problem on it.

**Comment by pedrobaeza** [comment]
It seems that you have half-updated your repo (maybe because you have some conflicts). In current version, there is a rounding_method argument, as you can see here:

https://github.com/OCA/OCB/blob/8.0/openerp/tools/float_utils.py#L32

So I close for now the issue.
