### ISSUE TITLE
[8.0] Crash after creating the database

### ISSUE THREAD

**Issue by syci** [OCA/OCB#66]
Rev: 1b53469 
On a clean installation after creating the database, it gives the following error when trying to load the [server]: 8069 / web

_QWebTemplateNotFound: External ID not found in the system: web.webclient_bootstrap_

The complete trace is:

2014-10-29 13:56:36,307 7123 ERROR v8_demo1 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo8/openobject-server/openerp/service/server.py", line 280, in app
    return self.app(e, s)
  File "/opt/odoo8/openobject-server/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo8/openobject-server/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo8/openobject-server/openerp/http.py", line 1215, in **call**
    return self.dispatch(environ, start_response)
  File "/opt/odoo8/openobject-server/openerp/http.py", line 1189, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/share/pyshared/werkzeug/wsgi.py", line 411, in **call**
    return self.app(environ, start_response)
  File "/opt/odoo8/openobject-server/openerp/http.py", line 1361, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/odoo8/openobject-server/openerp/http.py", line 1296, in get_response
    result = request.registry['ir.http']._handle_exception(e)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo8/openobject-server/openerp/http.py", line 596, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo8/openobject-server/openerp/http.py", line 1293, in get_response
    result.flatten()
  File "/opt/odoo8/openobject-server/openerp/http.py", line 1166, in flatten
    self.response.append(self.render())
  File "/opt/odoo8/openobject-server/openerp/http.py", line 1160, in render
    context=request.context)
  File "/opt/odoo8/openobject-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_ui_view.py", line 1007, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo8/openobject-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_qweb.py", line 184, in get_template
    raise_qweb_exception(QWebTemplateNotFound, message="Loader could not find template %r" % name, template=origin_template)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_qweb.py", line 182, in get_template
    xml_doc = qwebcontext.loader(name)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_ui_view.py", line 1005, in loader
    return self.read_template(cr, uid, name, context=context)
  File "/opt/odoo8/openobject-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in read_template

  File "/opt/odoo8/openobject-server/openerp/tools/cache.py", line 119, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_ui_view.py", line 849, in read_template
    view_id = self.pool['ir.model.data'].xmlid_to_res_id(cr, uid, xml_id, raise_if_not_found=True)
  File "/opt/odoo8/openobject-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_model.py", line 927, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(cr, uid, xmlid, raise_if_not_found)[1]
  File "/opt/odoo8/openobject-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_model.py", line 919, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo8/openobject-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in xmlid_lookup

  File "/opt/odoo8/openobject-server/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/opt/odoo8/openobject-server/openerp/addons/base/ir/ir_model.py", line 909, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
QWebTemplateNotFound: External ID not found in the system: web.webclient_bootstrap

**Comment by pedrobaeza** [comment]
This should be in https://github.com/odoo/odoo, not here.
