### ISSUE TITLE
test_crawl: raise ReadTimeout(e, request=request)

### ISSUE THREAD

**Issue by moylop260** [OCA/OCB#667]
Impacted versions:
11.0

Steps to reproduce:
See 11.0 travis build
https://travis-ci.org/OCA/OCB/builds/289552221#L7723

Current behavior:
```bash
2018-05-04 13:02:26,916 9108 ERROR odoo_test_crawl odoo.addons.website.tests.test_crawl: `   File "site-packages/requests/adapters.py", line 521, in send
2018-05-04 13:02:26,916 9108 ERROR odoo_test_crawl odoo.addons.website.tests.test_crawl: `     raise ReadTimeout(e, request=request)
2018-05-04 13:02:26,916 9108 ERROR odoo_test_crawl odoo.addons.website.tests.test_crawl: ` requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8069): Read timed out. (read timeout=1)
...
Traceback (most recent call last):
  File "/Users/moylop260/odoo_git/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/Users/moylop260/odoo_git/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.TestCursor object at 0x115775ac8>, 1)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/moylop260/odoo_git/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_layout_41
  File "<template>", line 2, in body_call_content_40
  File "/Users/moylop260/odoo_git/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/Users/moylop260/odoo_git/odoo/fields.py", line 1042, in determine_value
    record._prefetch_field(self)
  File "/Users/moylop260/odoo_git/odoo/models.py", line 2642, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/Users/moylop260/odoo_git/odoo/models.py", line 2586, in read
    self._read_from_database(stored, inherited)
  File "/Users/moylop260/odoo_git/odoo/models.py", line 2705, in _read_from_database
    cr.execute(query_str, params)
  File "/Users/moylop260/odoo_git/odoo/sql_db.py", line 154, in wrapper
    raise psycopg2.OperationalError(msg)
psycopg2.OperationalError: Unable to use a closed cursor.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/moylop260/odoo_git/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/Users/moylop260/odoo_git/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/moylop260/odoo_git/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View.get_view_id at 0x11454bb70>, 1, 'website.layout', (1,))
```

 - [![asciinema_test_crawl](https://asciinema.org/a/179738.png)](https://asciinema.org/a/179738)

Expected behavior:
Without errors

**Comment by simahawk** [comment]
Same story in [current build](https://travis-ci.org/OCA/OCB/builds/368384410#L7323)
```
KeyError: ('ir.qweb', <function IrQWeb._get_asset at 0x7f30bc9627b8>, 'web.assets_frontend', 'en_US', False, True, None, False, (1,))
```
@moylop260 have you already figured out the reason?

It seems that from time to time assets attachments retrieval is broken (I see this in my local instance too).

**Comment by moylop260** [comment]
Maybe a split of builds like as https://github.com/OCA/OCB/pull/730 is the solution

**Comment by pedrobaeza** [comment]
The split has been done, so I close.

**Comment by moylop260** [comment]
I have this issue again from last stable branch build.

Seems like as a TimeOut issue:
 - https://travis-ci.org/OCA/OCB/jobs/374175757#L6456

**Comment by simahawk** [comment]
@moylop260 the issue is not just for testing. It shows up also in debug mode. This is how it starts usually:

```bash
2018-05-04 12:14:04,063 1 INFO ? werkzeug: 192.168.64.1 - - [04/May/2018 12:14:04] "GET /website_sale_stock/static/src/xml/website_sale_stock_product_availability.xml?debug=1525436044042 HTTP/1.1" 200 -
2018-05-04 12:14:07,335 1 INFO odoodb odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [3067, 3066, 3065]
2018-05-04 12:14:08,800 1 INFO odoodb odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [3068]
2018-05-04 12:14:09,162 1 INFO odoodb werkzeug: 192.168.64.1 - - [04/May/2018 12:14:09] "GET /custom_website/static/images/facebook.png HTTP/1.1" 200 -
2018-05-04 12:14:09,163 1 ERROR odoodb odoo.sql_db: bad query: b'DELETE FROM ir_attachment WHERE id IN (3067, 3066, 3065)'
ERROR: could not serialize access due to concurrent update

2018-05-04 12:14:09,163 1 ERROR odoodb odoo.sql_db: bad query: b'DELETE FROM ir_attachment WHERE id IN (3067, 3066, 3065)'
ERROR: could not serialize access due to concurrent update

2018-05-04 12:14:09,163 1 ERROR odoodb odoo.sql_db: bad query: b'DELETE FROM ir_attachment WHERE id IN (3067, 3066, 3065)'
ERROR: could not serialize access due to concurrent update

2018-05-04 12:14:09,164 1 ERROR odoodb odoo.sql_db: bad query: b'DELETE FROM ir_attachment WHERE id IN (3067, 3066, 3065)'
ERROR: could not serialize access due to concurrent update

2018-05-04 12:14:09,166 1 ERROR odoodb odoo.sql_db: bad query: b'SELECT "ir_ui_view".id FROM "ir_ui_view" LEFT JOIN "website" as "ir_ui_view__website_id" ON ("ir_ui_view"."website_id" = "ir_ui_view__website_id"."id") WHERE ((("ir_ui_view"."active" = true)  AND  ("ir_ui_view"."key" = \'website.layout\'))  AND  (("ir_ui_view"."website_id" = 1)  OR  "ir_ui_view"."website_id" IS NULL )) ORDER BY "ir_ui_view__website_id"."id"   limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block

2018-05-04 12:14:09,166 1 ERROR odoodb odoo.sql_db: bad query: b'SELECT "ir_ui_view".id FROM "ir_ui_view" LEFT JOIN "website" as "ir_ui_view__website_id" ON ("ir_ui_view"."website_id" = "ir_ui_view__website_id"."id") WHERE ((("ir_ui_view"."active" = true)  AND  ("ir_ui_view"."key" = \'website.layout\'))  AND  (("ir_ui_view"."website_id" = 1)  OR  "ir_ui_view"."website_id" IS NULL )) ORDER BY "ir_ui_view__website_id"."id"   limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block

2018-05-04 12:14:09,169 1 ERROR odoodb odoo.sql_db: bad query: b'SELECT "ir_ui_view".id FROM "ir_ui_view" LEFT JOIN "website" as "ir_ui_view__website_id" ON ("ir_ui_view"."website_id" = "ir_ui_view__website_id"."id") WHERE ((("ir_ui_view"."active" = true)  AND  ("ir_ui_view"."key" = \'website.layout\'))  AND  (("ir_ui_view"."website_id" = 1)  OR  "ir_ui_view"."website_id" IS NULL )) ORDER BY "ir_ui_view__website_id"."id"   limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block

2018-05-04 12:14:09,172 1 ERROR odoodb odoo.sql_db: bad query: b'SELECT "ir_ui_view".id FROM "ir_ui_view" LEFT JOIN "website" as "ir_ui_view__website_id" ON ("ir_ui_view"."website_id" = "ir_ui_view__website_id"."id") WHERE ((("ir_ui_view"."active" = true)  AND  ("ir_ui_view"."key" = \'website.layout\'))  AND  (("ir_ui_view"."website_id" = 1)  OR  "ir_ui_view"."website_id" IS NULL )) ORDER BY "ir_ui_view__website_id"."id"   limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block

2018-05-04 12:14:09,184 1 ERROR odoodb odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/odoo/src/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/odoo/src/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/src/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb._get_asset at 0x7f8856079048>, 'web.assets_frontend', 'en_US', True, False, None, False, (1,))
[....]
```

**Comment by moylop260** [comment]
I think is an exception managing other exception.

I mean, for our case you can reproduce it using a short timeout
```patch
diff --git a/addons/website/tests/test_crawl.py b/addons/website/tests/test_crawl.py
index f5d4bc4ec12..ee0928491ae 100644
--- a/addons/website/tests/test_crawl.py
+++ b/addons/website/tests/test_crawl.py
@@ -38,7 +38,7 @@ class Crawler(odoo.tests.HttpCase):
             seen.add(url_slug)

         _logger.info("%s %s", msg, url)
-        r = self.url_open(url)
+        r = self.url_open(url, timeout=1)
         code = r.status_code
         self.assertIn(code, range(200, 300), "%s Fetching %s returned error response (%d)" % (msg, url, code))

```
Now run the test of `website`:
 - `~/odoo_git/odoo-bin -d odoo_test_crawl --db-filter=odoo_test_crawl -u website --test-enable --stop-after-init --log-level=error`

The first exception is `ReadTimeout`
```bash
2018-05-04 13:02:26,916 9108 ERROR odoo_test_crawl odoo.addons.website.tests.test_crawl: `   File "site-packages/requests/adapters.py", line 521, in send
2018-05-04 13:02:26,916 9108 ERROR odoo_test_crawl odoo.addons.website.tests.test_crawl: `     raise ReadTimeout(e, request=request)
2018-05-04 13:02:26,916 9108 ERROR odoo_test_crawl odoo.addons.website.tests.test_crawl: ` requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8069): Read timed out. (read timeout=1)
```

But the following exceptions are related with PostgreSQL and odoo cache:
```bash
Traceback (most recent call last):
  File "/Users/moylop260/odoo_git/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/Users/moylop260/odoo_git/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.TestCursor object at 0x115775ac8>, 1)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/moylop260/odoo_git/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_website_layout_41
  File "<template>", line 2, in body_call_content_40
  File "/Users/moylop260/odoo_git/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/Users/moylop260/odoo_git/odoo/fields.py", line 1042, in determine_value
    record._prefetch_field(self)
  File "/Users/moylop260/odoo_git/odoo/models.py", line 2642, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/Users/moylop260/odoo_git/odoo/models.py", line 2586, in read
    self._read_from_database(stored, inherited)
  File "/Users/moylop260/odoo_git/odoo/models.py", line 2705, in _read_from_database
    cr.execute(query_str, params)
  File "/Users/moylop260/odoo_git/odoo/sql_db.py", line 154, in wrapper
    raise psycopg2.OperationalError(msg)
psycopg2.OperationalError: Unable to use a closed cursor.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/moylop260/odoo_git/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/Users/moylop260/odoo_git/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/moylop260/odoo_git/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View.get_view_id at 0x11454bb70>, 1, 'website.layout', (1,))
```

Notice the message `During handling of the above exception, another exception occurred:` but the first is not the KeyError.

For our case is the timeout of the tests because the travisare low resources machines...

For your case you have a concurrent access. 2 cursors deleting the same record and the exception is that but the excepion of the exception is the `KeyError`
