### ISSUE TITLE
[7.0] Ascii problems on default python-reportlab package

### ISSUE THREAD

**Issue by cubells** [OCA/OCB#78]
Ubuntu 14.04
openerp 7.0 from github
localization: spanish

When try to print a sale order, I get:

```
2014-11-03 04:57:09,980 5730 ERROR database-name openerp.service.web_services: Exception: 'ascii' codec can't encode character u'\xf3' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/service/web_services.py", line 712, in go
    (result, format) = obj.create(cr, uid, ids, datas, context)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/report/report_sxw.py", line 449, in create
    fnct_ret = fnct(cr, uid, ids, data, report_xml, context)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/report/report_sxw.py", line 518, in create_source_pdf
    return self.create_single_pdf(cr, uid, ids, data, report_xml, context)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/report/report_sxw.py", line 540, in create_single_pdf
    pdf = create_doc(etree.tostring(processed_rml),rml_parser.localcontext,logo,title.encode('utf8'))
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/report/interface.py", line 206, in create_pdf
    obj.render()
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/report/render/render.py", line 59, in render
    self._result = self._render()
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/report/render/rml.py", line 41, in _render
    return rml2pdf.parseNode(self.rml, self.localcontext, images=self.bin_datas, path=self.path,title=self.title)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/report/render/rml2pdf/trml2pdf.py", line 1049, in parseNode
    r.render(fp)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/report/render/rml2pdf/trml2pdf.py", line 329, in render
    pt_obj.render(el)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/report/render/rml2pdf/trml2pdf.py", line 1029, in render
    self.doc_tmpl.build(fis)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 890, in build
    self.handle_flowable(flowables)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 773, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/frames.py", line 161, in _add
    w, h = flowable.wrap(aW, h)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/flowables.py", line 912, in wrap
    self.width, self.height = _listWrapOn(self._content,availWidth,self.canv)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/flowables.py", line 579, in _listWrapOn
    w,h = f.wrapOn(canv,availWidth,0xfffffff)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/flowables.py", line 121, in wrapOn
    w, h = self.wrap(aW,aH)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/tables.py", line 1173, in wrap
    self._calc(availWidth, availHeight)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/tables.py", line 625, in _calc
    self._calc_height(availHeight,availWidth,W=W)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/tables.py", line 556, in _calc_height
    dW,t = self._listCellGeom(v,w or self._listValueWidth(v),s)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/tables.py", line 397, in _listCellGeom
    vw, vh = v.wrapOn(canv, aW, aH)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/flowables.py", line 121, in wrapOn
    w, h = self.wrap(aW,aH)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/paragraph.py", line 1036, in wrap
    blPara = self.breakLines([first_line_width, later_widths])
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/paragraph.py", line 1244, in breakLines
    words[0:0] = _splitWord(word,maxWidth-spaceWidth-currentWidth,maxWidths,lineno,fontName,fontSize,self.encoding)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/paragraph.py", line 553, in _splitWord
    R.append(_SplitText(wordText))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 7: ordinal not in range(128)
2014-11-03 04:57:10,164 5730 ERROR database-name openerp.netsvc: ascii
Ubicació
7
8
ordinal not in range(128)
(<type 'exceptions.UnicodeEncodeError'>, UnicodeEncodeError('ascii', u'Ubicaci\xf3', 7, 8, 'ordinal not in range(128)'), <traceback object at 0x7f8c543b9c20>)
Traceback (most recent call last):
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/service/web_services.py", line 654, in dispatch
    res = fn(db, uid, *params)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/service/web_services.py", line 760, in exp_report_get
    return self._check_report(report_id)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/service/web_services.py", line 738, in _check_report
    netsvc.abort_response(exc, exc.message, 'warning', exc.traceback)
  File "/home/cubells/projectes/git/openerp70/src/server/openerp/netsvc.py", line 71, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: (u'ascii\nUbicaci\xf3\n7\n8\nordinal not in range(128)', (<type 'exceptions.UnicodeEncodeError'>, UnicodeEncodeError('ascii', u'Ubicaci\xf3', 7, 8, 'ordinal not in range(128)'), <traceback object at 0x7f8c543b9c20>))
```

The problem is that the package python-reportlab in ubuntu 14.04 has the version 3.x and openerp uses 2.7.x

I have to do a downgrade of python-reportlab in order to print works.

$ sudo aptitude purge python-reportlab
$ tar xzvf reportlab-2.7.tar.gz
$ cd reportlab-2.7/
$ sudo python setup.py install

**Comment by pedrobaeza** [comment]
Hi, Vicent, thanks for reporting.

Do you have any solution at OpenERP level?

**Comment by cubells** [comment]
It was a reportlab source code problem. This commit solved the problem:
https://bitbucket.org/rptlab/reportlab/commits/aed0e2af45460b241f7712bfcf68a948c658ba76

My server code was not updated.

I close this issue.

**Comment by rb3606** [comment]
i faced this problem. i tried everything. but same error. 
please help me.

 return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1441, in dispatch
    return response(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 1200, in **call**
    app_iter, status, headers = self.get_wsgi_response(environ)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 1190, in get_wsgi_response
    return app_iter, self.status, headers.to_wsgi_list()
  File "/usr/lib/python2.7/dist-packages/werkzeug/datastructures.py", line 1185, in to_wsgi_list
    return [(k, v.encode('latin1')) for k, v in self]
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 49-53: ordinal not in range(256)

**Comment by nanshihui** [comment]
i got the same  problem on reportlab==3.4.0
