### ISSUE TITLE
Error on button import click

### ISSUE THREAD

**Issue by butirpadi** [OCA/OCB#833]
Impacted versions: 9.0

Steps to reproduce: Test on Inventory -> Product Category -> Import Button Click

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

I try official repo from odoo/odoo github, there is no error like this.

this is the error message : 

`Odoo Server Error
Traceback (most recent call last):
  File "/media/eries/mywork/ERP/ocb9/openerp/http.py", line 659, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/eries/mywork/ERP/ocb9/openerp/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/media/eries/mywork/ERP/ocb9/openerp/http.py", line 332, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/media/eries/mywork/ERP/ocb9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/media/eries/mywork/ERP/ocb9/openerp/http.py", line 325, in checked_call
    result = self.endpoint(*a, **kw)
  File "/media/eries/mywork/ERP/ocb9/openerp/http.py", line 975, in __call__
    return self.method(*args, **kw)
  File "/media/eries/mywork/ERP/ocb9/openerp/http.py", line 525, in response_wrap
    response = f(*args, **kw)
  File "/media/eries/mywork/ERP/ocb9/addons/web/controllers/main.py", line 898, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/media/eries/mywork/ERP/ocb9/addons/web/controllers/main.py", line 890, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'create'`

**Comment by pedrobaeza** [comment]
I have just tried on http://3356481-9-0-d4d6de.runbot1.odoo-community.org and no error:

![seleccion_020](https://user-images.githubusercontent.com/7165771/52845281-fca8da80-3106-11e9-952b-1879f935d162.png)

Maybe it's due to a customization?
