### ISSUE TITLE
AttributeError 'super' no has attribute get_base_url

### ISSUE THREAD

**Issue by JoynalFrametOlimpo** [OCA/OCB#838]
Impacted versions: 12.0

Steps to reproduce: User->New->Save  after install web module

Current behavior:

Expected behavior:
.
Video/Screenshot link (optional):

After install web module in new project, there is error following to create new user.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record.id]
KeyError: 8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(8,).signup_url', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record.id]
KeyError: 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 963, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(9,).signup_url', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/var/lib/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/var/lib/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 1161, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 406, in read
    return super(Users, self).read(fields=fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2780, in read
    data[record][name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 967, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1078, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1034, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1027, in _compute_value
    self.compute(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 611, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5065, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 967, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1078, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1034, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1025, in _compute_value
    getattr(records, self.compute)()
  File "/var/lib/odoo/addons/auth_signup/models/res_partner.py", line 45, in _compute_signup_url
    result = self.sudo()._get_signup_url_for_action()
  File "/var/lib/odoo/addons/auth_signup/models/res_partner.py", line 58, in _get_signup_url_for_action
    base_url = partner.get_base_url()
  File "/var/lib/odoo/addons/website/models/res_partner.py", line 61, in get_base_url
    res = super(Partner, self).get_base_url()
AttributeError: 'super' object has no attribute 'get_base_url'

**Comment by pedrobaeza** [comment]
Is this something specific of OCB? This issue tracker is only for things that happen specifically in OCB and not in Odoo. Any way, it seems a deployment issue. Closing until further information.
