### ISSUE TITLE
Error during creation of invoice version 11

### ISSUE THREAD

**Issue by rjay1018** [OCA/OCB#911]
Impacted versions:11

Steps to reproduce: Creation of Invoice

Current behavior:Error Appears Error logs below
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo11/odoo-server/odoo/fields.py", line 940, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo11/odoo-server/odoo/api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: <odoo.models.NewId object at 0x7f5d5a77d318>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo11/odoo-server/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo11/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo11/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo11/odoo-server/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo11/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo11/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo11/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo11/odoo-server/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo11/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo11/OCB_test/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo11/OCB_test/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo11/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo11/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo11/odoo-server/odoo/models.py", line 5176, in onchange
    value = record[name]
  File "/opt/odoo11/odoo-server/odoo/models.py", line 4785, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo11/odoo-server/odoo/fields.py", line 946, in __get__
    self.determine_draft_value(record)
  File "/opt/odoo11/odoo-server/odoo/fields.py", line 1066, in determine_draft_value
    self._compute_value(record)
  File "/opt/odoo11/odoo-server/odoo/fields.py", line 1002, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo11/OCB_test/addons/account/models/account_invoice.py", line 436, in _get_sequence_number_next
    number_next = journal_sequence._get_current_sequence(sequence_date=sequence_date).number_next_actual
TypeError: _get_current_sequence() got an unexpected keyword argument 'sequence_date'
Expected behavior:

Video/Screenshot link (optional):
![Screenshot(3)](https://user-images.githubusercontent.com/5526244/75003565-2aa3c600-54a3-11ea-82ab-504fe81d213b.png)

**Comment by pedrobaeza** [comment]
Outdated code or something to be handled in odoo repo. As you have put the issue there, closing.
